version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/data/static/
      - media_volume:/data/media/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web_programming_gunicorn
    networks:
      - network

  web_programming_gunicorn:
    image: web_programming:1.0
    command: gunicorn web_programming.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/web_programming/static/
      - media_volume:/home/web_programming/media/
    expose:
      - 8000
    env_file:
      - /home/ubuntu/.env
    networks:
      - network

    
networks:
  network:

volumes:
  static_volume:
  media_volume:
