version: "3"

services:
  db:
    image: mysql
    restart: always
    container_name: mysql
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
networks:
  network:

volumes:
  db_data: